USE case_fb;

SELECT vd.ID_PESSOA, ps.NM_PESSOA, DATE_FORMAT(MAX(tp.DT_REF), "%d/%m/%Y") AS ULTIMA_COMPRA
FROM f_Vendas AS vd
LEFT JOIN d_Pessoa AS ps
ON (vd.ID_PESSOA = ps.ID_PESSOA)
LEFT JOIN d_Tempo AS tp
ON (vd.ID_TEMPO = tp.ID_TEMPO)
GROUP BY (ps.NM_PESSOA)
ORDER BY (ULTIMA_COMPRA);